### ISSUE TITLE
Curious about use case

### ISSUE THREAD

**Issue by lloydjatkinson** [fabasoad/twilio-fax-action#39]
Hi, I know this isn't really the purpose of issues but I'm so curious I just had to ask. How did this come about? What is it for?

Is it for some awkward client that wanted a fax of all the commits or something? That's about all I can think of...

**Comment by fabasoad** [comment]
Hi @lloydjatkinson! It's more about my imagination and possibilities that we can do using GitHub Actions 🙂 Not sure if it's used by someone in a real life project (I would probably be surprised as well if it is). Faxes are still popular in some countries though (in Japan for example) 🤔
